- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

# Setup front-end load balancer tier

- name: Setup load balancer tier for front-end servers
  hosts: load_balancers
  become: true
  gather_facts: false

  roles:
    - role: base-config
      vars:
        setup_role: "lbs"
    - role: lb-tier

# Setup application servers tier

- name: Setup application tier for application servers
  hosts: app_servers
  become: true
  gather_facts: false

  roles:
    - role: base-config
      vars: 
        setup_role: "apps"
    - role: app-tier

# Setup database tier

- name: Setup database tirer for database servers
  hosts: database_servers
  become: true
  gather_facts: false

  roles:
    - role: base-config
      vars:
         setup_role: "dbs"
    - role: db-tier

