- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

# Setup front-end load balancer tier

- name: Setup load balancer tier for front-end servers
  hosts: load_balancers
  become: true
  gather_facts: false

  roles:
    - {role: base-config, tags: ["base-config", "lbs"]}
    - {role: lb-tier, tags: ["lbs", "haproxy"]}

# Setup application servers tier

- name: Setup application tier for application servers
  hosts: app_servers
  become: true
  gather_facts: false

  roles:
    - {role: base-config, tags: ["base-config", "apps"]}
    - {role: app-tier, tags: ["apps", "tomcat"]}

# Setup database tier

- name: Setup database tirer for database servers
  hosts: database_servers
  become: true
  gather_facts: false

  roles:
    - {role: base-config, tags: ["base-config", "dbs"]}
    - {role: db-tier, tags: ["dbs", "postgres"]}
