- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

# Setup front-end load balancer tier

- name: setup load-balancer tier
  hosts: load_balancers
  become: true
  gather_facts: false
  tags:
    - load_balancers

  roles:
    - {name: base-config, tags: [base-config, lbs]}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: app_servers
  become: true
  gather_facts: false
  tags:
    - app_servers

  roles:
    - {name: base-config, tags: [base-config, apps]}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier

- name: setup database tier
  hosts: database_servers
  become: true
  gather_facts: false
  tags:
    - database_servers

  roles:
    - {name: base-config, tags: [base-config, dbs]}
    - {name: db-tier, tags: [dbs, postgres]}

