---
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: result

- name: Add host
  add_host:
    name: "{{ item.public_v4 }}"
    groups: "{{ item.metadata.group }}"
    # ansible_ssh_private_key_file: ~/.ssh/openstack.pem
    # ansible_ssh_user: cloud-user
  loop: "{{ result.openstack_servers | flatten(levels=1) }}"

- debug:
    var: groups

