---
- name: Add appdb1 IP address to app servers /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*appdb1$'
    line: "{{ groups.database_servers[0] }} appdb1"
    state: present

- name: Create flask user
  user:
    name: "{{ flask_user }}"
    state: present  

- name: "Install flask repo {{ flask_repo }}"
  git:
    repo: "{{ flask_repo }}"
    dest: "{{ flask_home }}/{{ flask_app_name }}"
    update: yes 
    force: yes
  tags:
    - git

- name: "Change flash repo owner to {{ flask_user }} recursively"      
  file: 
    dest: "{{ flask_home }}/{{ flask_app_name }}"
    owner: "{{ flask_user }}"

- name: virtualenv setup
  block:
    - name: Setup pre-requisite pip3 packages
      pip:
        name: "{{ pip_dependencies }}"
        state: latest
        executable: /usr/bin/pip3

    - name: "Create virtualenv {{ virtualenv_name }} for Flask"
      pip:
        requirements: "{{ flask_home }}/{{ flask_app_name }}/requirements.txt"
        virtualenv: "{{ virtualenv_home }}/{{ flask_app_name }}"
        virtualenv_site_packages: no
        virtualenv_command: /usr/local/bin/virtualenv
  tags:
    - venv
    - virtualenv  
      
- name: Initialize flask app database resources
  command: "{{ virtualenv_home }}/{{ flask_app_name }}/bin/python3 {{ flask_home }}/{{ flask_app_name }}/config.py"
  run_once: true

- name: start systemd app service
  systemd: 
    name: "{{ flask_app_name }}.service"
    state: restarted 
    enabled: yes

