---
# Initial, common, system setup steps
- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: enable repos
  yum_repository:
    name: internal
    description: Ansible bootcamp repo
    baseurl: http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo

- name: Include database tier role
  include_role:
    name: db-tier
  tags:
    - base-config
    - dbs
 
- name: Install Postgres packages for database tier
  package:
    name: "{{ __package }}"
    state: present
  loop: 
    - "{{ postgres_rhel7_repo }}"        
    - "{{ postgres_packages }}"
    - "{{ postgres_library }}"
  loop_control:
    loop_var: __package
  tags:
    - base-config
    - dbs

- name: Include app tier role
  include_role:
    name: app-tier
  tags:
    - base-config
    - apps

- name: Install flask packages for app tier
  package:
    name: "{{ app_yum_packages }}"
    state: present
  tags:
    - base-config 
    - apps

- name: Include load balancer tier role
  include_role:
    name: lb-tier
  tags:
    - base-config
    - lbs

- name: Install load balancer packages for load balancer tier
  package:
    name: "{{ load_balancer_packages }}"
    state: present
  tags:
    - base-config
    - lbs

