---
# Initial, common, system setup steps
- name: Enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

#- name: Enable repos
#  yum_repository:
#    name: internal
#    description: Ansible bootcamp repo
#    file: internal
#    baseurl: http://www.opentlc.com/download/ansible_bootcamp/repo/

- name: Install Postgres packages for database tier
  package:
    name: "{{ __package }}"
    state: present
  loop: 
    - "{{ postgres_rhel7_repo }}"        
    - "{{ postgres_packages }}"
    - "{{ postgres_library }}"
  loop_control:
    loop_var: __package
  when: setup_role == "dbs"

- name: Install flask packages for app tier
  package:
    name: "{{ app_yum_packages }}"
    state: present
  when: setup_role == "apps"

- name: Install load balancer packages for load balancer tier
  package:
    name: "{{ load_balancer_packages }}"
    state: present
  when: setup_role == "lbs"

